[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

# Redirecionamento de todas as rotas para /index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy para o endpoint do Google Cloud Functions
[[redirects]]
  from = "/api/*"
  to = "https://southamerica-east1-projeto-lambda-email.cloudfunctions.net/projeto-arch-4/:splat"
  status = 200
  force = true